version: "3"

services:
  {project_prefix}-db-service:
    image: {mysql_image}
    container_name: {project_prefix}-db-service
    environment:
      MYSQL_ROOT_PASSWORD: "{mysql_root_password}"
      MYSQL_DATABASE: "{mysql_database}"
      MYSQL_USER: "{mysql_user}"
      MYSQL_PASSWORD: "{mysql_password}"
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  {project_prefix}-www-service:
    image: {php_image}
    container_name: {project_prefix}-www-service
    volumes:
      - ./www_data:/var/www/html
    ports:
      - "8080:80"
    environment:
      VIRTUAL_HOST: {virtual_host}
      VIRTUAL_PORT: "80"

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy-service
    depends_on:
      - {project_prefix}-db-service
      - {project_prefix}-www-service
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
